# Generated by Django 4.2.3 on 2023-07-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the image', max_length=50, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, help_text='Captions of the image', max_length=250, null=True, verbose_name='Captions of the image')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('image', models.ImageField(blank=True, help_text='update the image', null=True, upload_to='images/')),
            ],
        ),
    ]
