# Generated by Django 4.2.3 on 2023-07-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
