# Generated by Django 4.2.3 on 2023-07-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give a title for product', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Describe about product', verbose_name='Description')),
                ('logo', models.ImageField(blank=True, upload_to='products/logoes/', verbose_name='Logo')),
                ('header', models.ImageField(blank=True, upload_to='products/header/', verbose_name='Header')),
                ('thumb', models.ImageField(blank=True, upload_to='products/thumbnails/', verbose_name='Thumbnail')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='Slug')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base Price')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateTimeField(blank=True, verbose_name='Expired Date')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='products.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload image for product', null=True, upload_to='products/gallery/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images_gallery', to='products.product')),
            ],
            options={
                'verbose_name': 'ProductImageGallery',
                'verbose_name_plural': 'ProductImageGallies',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.IntegerField(blank=True, default=0, verbose_name='Discount Value')),
                ('discount_unit', models.IntegerField(blank=True, default=0, verbose_name='Discount Unit')),
                ('valid_until', models.DateTimeField(blank=True, verbose_name='Valid until')),
                ('coupon_code', models.CharField(blank=True, max_length=15, verbose_name='Coupon Code')),
                ('minimun_order_value', models.IntegerField(blank=True, default=0, verbose_name='Minimum Order Value')),
                ('maximum_discount_amount', models.IntegerField(blank=True, default=0, verbose_name='Maximum Discount Amount')),
                ('is_redeem_allowed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='products.product', verbose_name='Product Discount')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='slug')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.producttag', verbose_name='Product Tag'),
        ),
    ]
