# Generated by Django 4.2.3 on 2023-07-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, help_text='Give a title for product', max_length=100, verbose_name='Title'),
        ),
    ]
