# Generated by Django 4.2.3 on 2023-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug for the service', max_length=150, null=True, unique=True),
        ),
    ]
