# Generated by Django 4.2.3 on 2023-07-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_serviceprice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_price', to='services.service'),
            preserve_default=False,
        ),
    ]
