# Generated by Django 4.2.3 on 2023-07-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogpost_header_image_alter_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Size = 1500px x 500px', upload_to='media/blogs/header', verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=75, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Size = 405px x 305px', upload_to='media/blogs/thumbs', verbose_name='Thumbnail'),
        ),
    ]
